/**
 * Day sheets.
 *
 * ---------------------------------------------------------------------------
 * WHY THIS IS THE MOST IMPORTANT REPORT IN THE BUILDING
 * ---------------------------------------------------------------------------
 * The arena physically runs on this paper. The announcer reads it, the chute
 * boss works from it, the gate man calls off it, the judges follow it and the
 * secretary reconciles against it. A rodeo can lose its network, its tablets
 * and its power and still run a performance, because somebody printed the day
 * sheet. Everything else in this repository is a convenience by comparison.
 *
 * So it is generated by a pure function with no I/O, no clock and no database,
 * for the same reason the payout engine is: it has to produce the identical
 * sheet from the identical data, on a server, in a browser, or offline in an
 * arena office with no signal.
 *
 * ---------------------------------------------------------------------------
 * WHAT GOES ON IT, AND WHY EACH THING IS THERE
 * ---------------------------------------------------------------------------
 *   Position        The run order. This is the draw, and it is the reason the
 *                   sheet exists.
 *   Back number     What the announcer actually says and what the judge writes
 *                   down. Not the contestant id.
 *   Stock           Which animal. A roughstock event without this is unrunnable.
 *   Horse           Barrels, breakaway and roping turn on which horse ran, and
 *                   the horse's own record depends on capturing it here.
 *   Partner         Team roping is two people on one run.
 *   Flags           Turned out, scratched, re-ride pending, medical release.
 *                   The gate man needs to know not to wait for somebody who
 *                   went home.
 *   Drag marks      WPRA requires the arena dragged every N runs in barrel
 *                   racing. A sheet that does not show where the drags fall
 *                   makes the arena crew count rows by hand, in the dark.
 */

export type RunFlag =
  | 'turned_out'
  | 'scratched'
  | 'no_show'
  | 'reride_pending'
  | 'medical_release'
  | 'vet_release'
  | 'slack';

/** One contestant's scheduled run, as it appears on the sheet. */
export interface DaySheetRun {
  position: number;
  /** The entry this run belongs to — what a score is recorded against. */
  entry_id: string;
  back_number: string | null;
  contestant_id: string;
  contestant_name: string;
  partner_name: string | null;
  /** The contestant's own horse, where the event uses one. */
  horse_name: string | null;
  /** Drawn stock: bull, bronc, calf or steer. */
  stock_name: string | null;
  stock_brand: string | null;
  go_round: number;
  flags: RunFlag[];
  /** True when nothing should be waited for at the gate. */
  is_scratched: boolean;
  notes: string | null;
  /**
   * The release reason stored on the entry, if any. A release with no flag of
   * its own (stock issue, weather) still prints its reason, so the gate man
   * never reads a scratched run with a blank note.
   */
  release_type: string | null;
}

/** A drag inserted into the run order. */
export interface DragMark {
  /** Runs completed before the drag. */
  after_position: number;
  condensed: boolean;
}

export interface DaySheetSection {
  rodeo_event_id: string;
  event_type: string;
  event_label: string;
  scoring_mode: 'judged' | 'timed';
  is_roughstock: boolean;
  go_round: number;
  runs: DaySheetRun[];
  drags: DragMark[];
  /** The drag interval the marks were counted with, so a copy can recount them. */
  drag_every: number | null;
  condensed_drag: boolean;
  /** Runs that will actually happen — scratches excluded. */
  live_count: number;
  entered_count: number;
}

export interface DaySheetPersonnel {
  role: string;
  name: string;
  /** Null when the association does not require a card for this role. */
  card_number: string | null;
  carded: boolean;
}

export interface DaySheet {
  rodeo_id: string;
  rodeo_name: string;
  performance_id: string | null;
  performance_name: string;
  performance_type: 'performance' | 'slack' | 'short_go' | 'finals';
  /** ISO date. Never a Date object — this file reads no clock. */
  date: string;
  scheduled_start: string | null;
  venue: string | null;
  sanctioned_by: string[];
  personnel: DaySheetPersonnel[];
  sections: DaySheetSection[];
  total_runs: number;
  /** Rendered at the foot of every page so a lost sheet is identifiable. */
  footer: string;
}

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

export interface DaySheetEntry {
  entry_id: string;
  rodeo_event_id: string;
  contestant_id: string;
  contestant_name: string;
  partner_name?: string | null;
  back_number?: string | null;
  horse_name?: string | null;
  go_round: number;
  /** Draw position within this event and round. Null = not yet drawn. */
  draw_position: number | null;
  performance_id?: string | null;
  status: string;
  release_type?: string | null;
  reride_pending?: boolean;
  notes?: string | null;
}

export interface DaySheetStock {
  entry_id: string;
  go_round: number;
  animal_name: string;
  brand_number?: string | null;
}

export interface DaySheetEvent {
  rodeo_event_id: string;
  event_type: string;
  event_label: string;
  scoring_mode: 'judged' | 'timed';
  is_roughstock: boolean;
  sort_order: number;
  /** WPRA-style arena maintenance: drag every N runs. Null = no drags. */
  drag_every?: number | null;
  condensed_drag?: boolean;
}

export interface DaySheetInput {
  rodeo_id: string;
  rodeo_name: string;
  venue?: string | null;
  sanctioned_by?: string[];
  performance: {
    id: string | null;
    name: string;
    type: 'performance' | 'slack' | 'short_go' | 'finals';
    date: string;
    scheduled_start?: string | null;
    /** Overrides the per-event drag interval for this performance. */
    arena_dragged_after?: number | null;
    condensed_drag?: boolean;
  };
  events: DaySheetEvent[];
  entries: DaySheetEntry[];
  stock?: DaySheetStock[];
  personnel?: DaySheetPersonnel[];
  /** Only these go-rounds appear. Empty = all of them. */
  go_rounds?: number[];
}

// A release means he is not running: classifyTurnout stores 'medical_release'
// for every excused reason (medical, vet_release, stock_issue, weather).
const SCRATCHED_STATUSES = new Set(['scratched', 'turned_out', 'no_show', 'medical_release']);

function flagsFor(entry: DaySheetEntry, performanceType: string): RunFlag[] {
  const flags: RunFlag[] = [];
  if (entry.status === 'turned_out') flags.push('turned_out');
  if (entry.status === 'scratched') flags.push('scratched');
  if (entry.status === 'no_show') flags.push('no_show');
  if (entry.reride_pending) flags.push('reride_pending');
  if (entry.release_type === 'medical') flags.push('medical_release');
  if (entry.release_type === 'vet_release') flags.push('vet_release');
  if (performanceType === 'slack') flags.push('slack');
  return flags;
}

/**
 * Where the drags fall.
 *
 * Counted over LIVE runs, not entered runs. A scratch does not stir up the
 * ground, so counting it towards a drag would put the tractor out early and
 * every subsequent drag in the wrong place.
 */
const OUT_FLAGS: RunFlag[] = ['turned_out', 'scratched', 'no_show', 'medical_release', 'vet_release'];

/**
 * The stored release reason, for a scratched run that has no flag saying why
 * (a stock issue or weather release). Empty when a flag already says it.
 */
export function releaseNote(run: Pick<DaySheetRun, 'is_scratched' | 'flags' | 'release_type'>): string {
  if (!run.is_scratched || !run.release_type) return '';
  if (run.flags.some((f) => OUT_FLAGS.includes(f))) return '';
  return run.release_type.replace(/_/g, ' ').toUpperCase();
}

export function dragMarks(
  liveRunCount: number,
  every: number | null | undefined,
  condensed = false,
): DragMark[] {
  if (!every || every <= 0) return [];
  const marks: DragMark[] = [];
  for (let n = every; n < liveRunCount; n += every) {
    marks.push({ after_position: n, condensed });
  }
  return marks;
}

/**
 * Build the sheet.
 *
 * Sorting is total and explicit — event sort order, then go-round, then draw
 * position, then name — so the same input always produces the same paper. An
 * undrawn entry sorts last rather than being dropped: a secretary needs to see
 * that somebody is missing from the draw, and a sheet that silently omits them
 * is how a contestant gets left out of a performance.
 */
export function buildDaySheet(input: DaySheetInput): DaySheet {
  const stockByEntry = new Map<string, DaySheetStock>();
  for (const s of input.stock ?? []) {
    stockByEntry.set(`${s.entry_id}:${s.go_round}`, s);
  }

  const wantedRounds = new Set(input.go_rounds ?? []);
  const perfId = input.performance.id;

  const sections: DaySheetSection[] = [];

  for (const event of [...input.events].sort((a, b) => a.sort_order - b.sort_order)) {
    const forEvent = input.entries.filter((e) => {
      if (e.rodeo_event_id !== event.rodeo_event_id) return false;
      if (wantedRounds.size > 0 && !wantedRounds.has(e.go_round)) return false;
      // A performance-scoped sheet shows only that performance. A sheet with
      // no performance id is the whole rodeo.
      if (perfId !== null && (e.performance_id ?? null) !== perfId) return false;
      return true;
    });

    if (forEvent.length === 0) continue;

    const byRound = new Map<number, DaySheetEntry[]>();
    for (const e of forEvent) {
      const bucket = byRound.get(e.go_round) ?? [];
      bucket.push(e);
      byRound.set(e.go_round, bucket);
    }

    for (const round of [...byRound.keys()].sort((a, b) => a - b)) {
      const ordered = [...(byRound.get(round) ?? [])].sort((a, b) => {
        const ap = a.draw_position;
        const bp = b.draw_position;
        if (ap === null && bp === null) {
          return a.contestant_name.localeCompare(b.contestant_name);
        }
        if (ap === null) return 1; // undrawn sorts last, never disappears
        if (bp === null) return -1;
        if (ap !== bp) return ap - bp;
        return a.contestant_name.localeCompare(b.contestant_name);
      });

      let position = 0;
      const runs: DaySheetRun[] = ordered.map((e) => {
        const scratched = SCRATCHED_STATUSES.has(e.status);
        // Scratches keep their place on the sheet but do not consume a running
        // number: the announcer counts down live runs.
        if (!scratched) position += 1;
        const stock = stockByEntry.get(`${e.entry_id}:${e.go_round}`);
        return {
          position: scratched ? 0 : position,
          entry_id: e.entry_id,
          back_number: e.back_number ?? null,
          contestant_id: e.contestant_id,
          contestant_name: e.contestant_name,
          partner_name: e.partner_name ?? null,
          horse_name: e.horse_name ?? null,
          stock_name: stock?.animal_name ?? null,
          stock_brand: stock?.brand_number ?? null,
          go_round: e.go_round,
          flags: flagsFor(e, input.performance.type),
          is_scratched: scratched,
          notes: e.notes ?? null,
          release_type: e.release_type ?? null,
        };
      });

      const live = runs.filter((r) => !r.is_scratched).length;
      const dragEvery =
        input.performance.arena_dragged_after ?? event.drag_every ?? null;
      const condensed = input.performance.condensed_drag ?? event.condensed_drag ?? false;

      sections.push({
        rodeo_event_id: event.rodeo_event_id,
        event_type: event.event_type,
        event_label: event.event_label,
        scoring_mode: event.scoring_mode,
        is_roughstock: event.is_roughstock,
        go_round: round,
        runs,
        drags: dragMarks(live, dragEvery, condensed),
        drag_every: dragEvery,
        condensed_drag: condensed,
        live_count: live,
        entered_count: runs.length,
      });
    }
  }

  const totalRuns = sections.reduce((t, s) => t + s.live_count, 0);

  return {
    rodeo_id: input.rodeo_id,
    rodeo_name: input.rodeo_name,
    performance_id: perfId,
    performance_name: input.performance.name,
    performance_type: input.performance.type,
    date: input.performance.date,
    scheduled_start: input.performance.scheduled_start ?? null,
    venue: input.venue ?? null,
    sanctioned_by: input.sanctioned_by ?? [],
    personnel: input.personnel ?? [],
    sections,
    total_runs: totalRuns,
    footer: `${input.rodeo_name} — ${input.performance.name} — ${input.performance.date}`,
  };
}

/**
 * The sheet as fixed-width text.
 *
 * Not a nicety. An arena office has a cheap printer and no design department,
 * and a monospaced sheet prints identically from every browser, survives being
 * faxed, and can be read at arm's length under a floodlight.
 */
export function renderDaySheetText(sheet: DaySheet, width = 96): string {
  const line = (ch: string) => ch.repeat(width);
  const out: string[] = [];

  out.push(sheet.rodeo_name.toUpperCase());
  out.push(`${sheet.performance_name}  ·  ${sheet.date}${
    sheet.scheduled_start ? `  ·  ${sheet.scheduled_start}` : ''
  }`);
  if (sheet.venue) out.push(sheet.venue);
  if (sheet.sanctioned_by.length > 0) {
    out.push(`Approved: ${sheet.sanctioned_by.join(', ')}`);
  }
  if (sheet.personnel.length > 0) {
    out.push(
      sheet.personnel
        .map(
          (p) =>
            `${p.role}: ${p.name}${p.card_number ? ` (#${p.card_number})` : ''}`,
        )
        .join('   '),
    );
  }
  out.push(line('='));

  for (const section of sheet.sections) {
    out.push('');
    const roundLabel =
      section.go_round > 1 ? `  —  Round ${section.go_round}` : '';
    out.push(`${section.event_label.toUpperCase()}${roundLabel}   (${section.live_count} up)`);
    out.push(line('-'));
    out.push(
      pad('#', 4) +
        pad('BACK', 6) +
        pad('CONTESTANT', 26) +
        pad('PARTNER', 20) +
        pad(section.is_roughstock ? 'STOCK' : 'HORSE', 20) +
        'NOTES',
    );

    const dragAfter = new Map(section.drags.map((d) => [d.after_position, d]));

    for (const run of section.runs) {
      const mount = section.is_roughstock
        ? [run.stock_name, run.stock_brand && `#${run.stock_brand}`]
            .filter(Boolean)
            .join(' ')
        : run.horse_name ?? '';
      const notes = [
        ...run.flags.map((f) => f.replace(/_/g, ' ').toUpperCase()),
        releaseNote(run),
        run.notes ?? '',
      ]
        .filter(Boolean)
        .join(' · ');

      out.push(
        pad(run.is_scratched ? '--' : String(run.position), 4) +
          pad(run.back_number ?? '', 6) +
          pad(run.contestant_name, 26) +
          pad(run.partner_name ?? '', 20) +
          pad(mount, 20) +
          notes,
      );

      const drag = dragAfter.get(run.position);
      if (drag && !run.is_scratched) {
        out.push(
          `    ${'~'.repeat(20)} DRAG${drag.condensed ? ' (condensed)' : ''} ${'~'.repeat(20)}`,
        );
      }
    }
  }

  out.push('');
  out.push(line('='));
  out.push(`${sheet.footer}    Total runs: ${sheet.total_runs}`);
  return out.join('\n');
}

function pad(value: string, width: number): string {
  const v = value.length > width - 1 ? value.slice(0, width - 2) + '…' : value;
  return v.padEnd(width, ' ');
}
